
version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - /home/lucaomartins/projects/my-poll/postgresql/data
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge