version: '3.8'

services:
  db:
    image: postgres
    ports:
      - 15432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=poll_app
    env_file:
      - .env
  web:
    build: ./services/web
    command: python run.py run -h 0.0.0.0
    links:
      - db
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - .env

volumes:
  postgres_data:
